# Numpy


import numpy as np

## Create a vector

In [2]:
import numpy as np

vector = np.array([5, 10, 15, 20])

## Create a matrix using a list of lists:

In [ ]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

## Get number of elements in an array

In [4]:
import numpy 

matrix = numpy.array([[5, 10, 15], [20, 25, 30]])
print(matrix.shape)
#results in the tuple (2,3) indicating that matrix has 2 rows and 3 columns.

(2, 3)


## Read in datasets using the numpy.genfromtxt() function:

In [5]:
nfl = numpy.genfromtxt("data/data.csv", delimiter=",")

OSError: data.csv not found.

## Get data type of a NumPy array using the dtype property

In [6]:
numbers = np.array([1, 2, 3, 4])
print(numbers.dtype)

int64


## Index a NumPy vector 
(like regular lists):

In [7]:
vector = np.array([5, 10, 15, 20])
print(vector[0])

5


## Indexing NumPy matrices 
(like indexing lists of lists):

In [8]:
matrix = np.array([
                 [5, 10, 15], 
                [20, 25, 30]
                 ])
matrix[1,2]

30

## Select one whole dimension, and an element from the other:

In [9]:
matrix = np.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
matrix[:,1]

array([10, 25, 40])

## Select one whole dimension, and a slice of the other
we need to use special notation: 

In [19]:
matrix = np.array([ [5, 10, 15], 
                   [20, 25, 30],
                   [35, 40, 45]])
matrix[:,0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

## Select rows by specifying a colon in the columns area: 

In [14]:
matrix[1:3,:]
# selects rows 1 and 2, and all of the columns.

array([[20, 25, 30],
       [35, 40, 45]])

## Select a single value along an entire dimension:

In [15]:
matrix[1:3,1]
#selects rows 1 and 2 and column 1

array([25, 40])

## Slice along both dimensions

In [18]:
matrix = np.array([[5, 10, 15], 
                   [20, 25, 30],
                   [35, 40, 45]])
matrix[1:3,0:2]
# selects rows with index 1 and 2, and columns with index 0 and 1:

array([[20, 25],
       [35, 40]])

## Select elements in vectors using Boolean vectors:
This allows us to conditionally select certain elements in vectors

In [23]:
#For Vectors:

vector = numpy.array([5, 10, 15, 20])
equal_to_ten = (vector == 10)
# Compares vector to the value 10, 
# which generates a Boolean vector [False, True, False, False]. 
# It assigns the result to equal_to_ten

print(vector[equal_to_ten])
# Uses equal_to_ten to only select elements in vector where equal_to_ten is True.


[10]


## Select elements in matrices using Boolean vectors
This allows us to conditionally select certain rows in matrices.

In [22]:
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
second_column_25 = (matrix[:,1] == 25)
# Uses second_column_25 to select any rows in matrix where second_column_25 is True.
#We selected a single row from matrix, which was returned in a new matrix

print(matrix[second_column_25, :])

[[20 25 30]]


## Select Elements with Multiple conditions:

In [24]:
is_algeria_and_1986 = (world_alcohol[:,2] == "Algeria") & (world_alcohol[:,0] == "1986")
rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986,:]
print(rows_with_algeria_and_1986)

NameError: name 'world_alcohol' is not defined

## Replace values

In [ ]:
with_1986_true = (world_alcohol[:,0] == "1986") 
world_alcohol[with_1986_true,0] = '2014'

with_wine_true = (world_alcohol[:,3] =="Wine")
world_alcohol[with_wine_true,3] = "Grog"


## Replace empty Strings

In [ ]:
is_value_empty = (world_alcohol[:,4] == '')
world_alcohol[is_value_empty,4] = "0"

## Convert the data type

In [ ]:
vector = numpy.array(["1", "2", "3"])
vector = vector.astype(float)

## Computations on values in Vector:

In [3]:
vector = numpy.array([5, 10, 15, 20])
vector.sum()
# add together all of the elements in vector, and result in 50.

total_alcohol = alcohol_consumption.sum()
average_alcohol = alcohol_consumption.mean()

NameError: name 'numpy' is not defined

## Computation on values in Matrices
The axis dictates which dimension we perform the operation on. 
1 means that we want to 	perform the operation on each row, and 0 means on each column. 


In [25]:
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
matrix.sum(axis=1)
# This would compute the sum for each row

array([ 30,  75, 120])

# Numpy Arrays Manipulation for Linear Systems:


## To swap 2 rows
NumPy ndarray object, we need to use double bracket notation to specify the row ordering change:

## To Multiply a row by a nonzero constant:

In [ ]:
# Multipy the second row by 2.
matrix[1] = 2*matrix[1]

matrix =  np.asarray([
    [1, 3],
    [50, 2]  
], dtype=np.float32)

# Swap the second row (at index value 1) with the first row (at index value 0).
matrix = matrix[[1,0]]

## To add one row to another row:

we need to add both rows then assign it back to row we want to overwrite:


In [ ]:
# Add the second row to the first row.
matrix[1] = matrix[1] + matrix[0]

## Chaining:

We can combine and chain these rules to perform more complex row transformations:

In [ ]:
matrix[1] = 0.5*matrix[2] + matrix[1] + matrix[3]

## Vectors:

Typically, a vector is visualized on a coordinate grid using arrows, not using coordinates. For a vector containing two elements, the first value describes the
x coordinate while the second value describes the y coordinate. Vectors are usually drawn from the origin (0,0) to the point described by the vector:

Arrows are used to visualize individual vectors because they emphasize the 2 key properties of a vector -- direction and magnitude. The direction of a vector describes the way its pointing while the magnitude describes its length.

Visualise in matplotlib using ‘quiver’.

X and Y correspond to the (x,y) coordinates we want the vector to start at and U and V correspond to the (x,y) coordinates we want the vector to end at.
Setting angles to 'xy' lets matplotlib know we want the angle of the vector to be between the points we specified. The scale_units and scale parameters lets us specify custom scaling parameters for the vectors. When plotting vectors, we always want to use these 3 values for the parameters.



In [2]:
plt.quiver(0, 0, 1, 2, angles='xy', scale_units='xy', scale=1, color='blue')

NameError: name 'plt' is not defined

## Adding/Multiplying:

In [ ]:
vector_one = np.asarray([
    [1],
    [2],
    [1]
], dtype=np.float32)

vector_two = np.asarray([
    [3],
    [0],
    [1]
], dtype=np.float32)

vector_linear_combination = (vector_one * 2) + (vector_two * 5)


## dot product:

Dot product is similar to multiplication, but involves multiplying the elements in the vectors in a specific way. Both of these vectors need to contain the same number of elements, a requirement the other operations we've learned so far have as well. To compute the dot product, we need to sum the products of the 2 values in each position in each vector. the result of a dot product is a scalar value, not a vector. 

The main quirk is that one of the two vectors need to be represented as a row vector while the other a column vector:

In [ ]:
vector_dp = np.dot(vector_one[:,0], vector_two)

## Advanced Matrix Algebra

In [ ]:
## 2. Matrix Vector Multiplication ##

matrix_a = np.asarray([
    [0.7,3,9],
    [1.7,2,9],
    [0.7,9,2]
    ], dtype=np.float32)

vector_b = np.asarray([
    [1],
    [2],
    [1]
    ], dtype=np.float32)

ab_product = np.dot(matrix_a, vector_b)
print(ab_product)

## 3. Matrix Multiplication ##

matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]
], dtype=np.float32)

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)

product_ab = np.dot(matrix_a, matrix_b)
product_ba = np.dot(matrix_b, matrix_a)

print(product_ab)
print(product_ba)

## 4. Matrix Transpose ##

matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]
], dtype=np.float32)

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)

transpose_a = np.transpose(matrix_a)
transpose_b = np.transpose(matrix_b)
print(transpose_a)

print(np.transpose(transpose_a))

trans_ab = np.dot(transpose_a, transpose_b)
trans_ba = np.dot(transpose_b, transpose_a)

product_ab = np.dot(matrix_a,matrix_b)
print(np.transpose(product_ab))




## 5. Identity Matrix ##

i_2 = np.identity(2)
i_3 = np.identity(3)

matrix_33 = np.asarray([
                [1,2,3],
                [4,5,6],
                [7,8,9]
            ])

matrix_23 = np.asarray([
                [1,2,3],
                [4,5,6]
            ])
identity_33 = np.dot(i_3, matrix_33)
identity_23 = np.dot(i_2, matrix_23)

print(identity_33)
print(identity_23)


## 6. Matrix Inverse ##

matrix_a = np.asarray([
    [1.5, 3],
    [1, 4]
])

def matrix_inverse_two(mat):
    
    det = (mat[0,0]*mat[1,1] - mat[0,1]*mat[1,0])
    
    if det == 0:
        raise ValueError("The matrix isn't invertible")
        
    right_mat = np.asarray([
        [mat[1,1], -mat[0,1]],
        [-mat[1,0], mat[0,0]]
    ])
    
    inv_mat = np.dot(1/det, right_mat)
    
    return inv_mat


inverse_a = matrix_inverse_two(matrix_a)

i_2 = np.dot(inverse_a, matrix_a)

print(i_2)

## 7. Solving The Matrix Equation ##

matrix_a = np.asarray([
    [30, -1],
    [50, -1]
    ])

vector_b = np.asarray([
    [-1000],
    [-100]
    ])

solution_x = np.dot(np.linalg.inv(matrix_a), vector_b)

print(solution_x)

## 8. Determinant For Higher Dimensions ##

matrix_22 = np.asarray([
    [8, 4],
    [4, 2]
])

matrix_33 = np.asarray([
    [1, 1, 1],
    [1, 1, 6],
    [7, 8, 9]
])

det_22 = np.linalg.det(matrix_22)
det_33 = np.linalg.det(matrix_33)

## Examples

In [ ]:

## 9. Total Annual Alcohol Consumption ##

is_canada_1986 = (world_alcohol[:,0] == "1986") & (world_alcohol[:,2] == "Canada")
canada_1986 = world_alcohol[is_canada_1986,:]

consumption = canada_1986[:,4]
empty_consumption = consumption == ""
consumption[empty_consumption] = "0"
canada_alcohol = consumption.astype(float)
total_canadian_drinking = canada_alcohol.sum()


## 10. Calculating Consumption for Each Country ##

totals = {}

#find rows where year is 1989
is_year = world_alcohol[:,0] == "1989"
year = world_alcohol[is_year,:]


for item in countries:
    is_country = year[:,2] == item
    country_consumption = year[is_country,:]
    consumption = country_consumption[:,4]
    empty_consumption = consumption == ""
    consumption[empty_consumption] = "0"
    consumption_col = consumption.astype(float)
    sum_consumption = consumption_col.sum()
    
    if item in totals:
        totals[item] = totals[item] + sum_consumption
    else:
        totals[item] = sum_consumption

print(totals)

## 11. Finding the Country that Drinks the Most ##

highest_value = 0
highest_key = None

for item in totals:
    if totals[item] > highest_value:
        highest_value = totals[item]
        highest_key = item
        
        
print(highest_value)
print(highest_key)